export enum EnvVariablesKey {
  POSTGRES_USER = 'POSTGRES_USER',
  POSTGRES_PASSWORD = 'POSTGRES_PASSWORD',
  POSTGRES_DB = 'POSTGRES_DB',
  SWAGGER_KEY = 'SWAGGER_KEY',
  REST_API_PORT = 'REST_API_PORT',
}
